version: "3.8"
services:
  blog-educacional:
    build: .
    container_name: blog-educacional-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env